spring:
  application:
    name: izilearn
  threads:
    virtual: true
  profiles:
    active: test
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  server:
    error:
      include-stacktrace: on_param

springdoc:
  swagger-ui:
    path: /swagger-ui
    enabled: true
    display-request-duration: true
    operationsSorter: method
  api-docs:
    path: /api-docs